require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task :default => [:build, :spec]

desc 'Compile the extension from source ready for packaging'
task :build_from_source do
  cargo_dir = File.expand_path('../../../libpasta/libpasta-capi/', __FILE__)
  pb_loc = File.expand_path('../../../pasta-bindings/', __FILE__)
  Dir.chdir(pb_loc) do
    sh "USE_STATIC=1 STATIC_LIBPASTA=#{cargo_dir}/target/release/libpasta.a make ruby"
  end
  cp "#{pb_loc}/ruby/pasta.so", "lib/"
end
